# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_M_W(object):
    def setupUi(self, M_W):
        M_W.setObjectName(_fromUtf8("M_W"))
        M_W.resize(834, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        M_W.setFont(font)
        self.centralwidget = QtGui.QWidget(M_W)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(500, 200))
        self.frame_2.setMaximumSize(QtCore.QSize(400, 200))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 20, 131, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.qnum = QtGui.QLineEdit(self.frame_2)
        self.qnum.setGeometry(QtCore.QRect(170, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.qnum.setFont(font)
        self.qnum.setText(_fromUtf8(""))
        self.qnum.setMaxLength(3)
        self.qnum.setFrame(True)
        self.qnum.setObjectName(_fromUtf8("qnum"))
        self.run_btn = QtGui.QPushButton(self.frame_2)
        self.run_btn.setGeometry(QtCore.QRect(370, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semibold"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.run_btn.setFont(font)
        self.run_btn.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.run_btn.setObjectName(_fromUtf8("run_btn"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 121, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pop_len = QtGui.QLineEdit(self.frame_2)
        self.pop_len.setGeometry(QtCore.QRect(170, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pop_len.setFont(font)
        self.pop_len.setMaxLength(20)
        self.pop_len.setFrame(True)
        self.pop_len.setObjectName(_fromUtf8("pop_len"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(0, 100, 121, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.mut_rate = QtGui.QLineEdit(self.frame_2)
        self.mut_rate.setGeometry(QtCore.QRect(170, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mut_rate.setFont(font)
        self.mut_rate.setMaxLength(2)
        self.mut_rate.setFrame(True)
        self.mut_rate.setObjectName(_fromUtf8("mut_rate"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 140, 111, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.max_iter = QtGui.QLineEdit(self.frame_2)
        self.max_iter.setGeometry(QtCore.QRect(170, 140, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.max_iter.setFont(font)
        self.max_iter.setMaxLength(20)
        self.max_iter.setFrame(True)
        self.max_iter.setObjectName(_fromUtf8("max_iter"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(200, 100, 21, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.stop_btn = QtGui.QPushButton(self.frame_2)
        self.stop_btn.setGeometry(QtCore.QRect(370, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semibold"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.log_output = QtGui.QPlainTextEdit(self.frame)
        self.log_output.setMinimumSize(QtCore.QSize(500, 0))
        self.log_output.setMaximumSize(QtCore.QSize(500, 16777215))
        self.log_output.setReadOnly(True)
        self.log_output.setObjectName(_fromUtf8("log_output"))
        self.gridLayout_2.addWidget(self.log_output, 1, 0, 2, 1)
        self.log_shape = QtGui.QLabel(self.frame)
        self.log_shape.setMinimumSize(QtCore.QSize(300, 300))
        self.log_shape.setMaximumSize(QtCore.QSize(700, 700))
        self.log_shape.setText(_fromUtf8(""))
        self.log_shape.setAlignment(QtCore.Qt.AlignCenter)
        self.log_shape.setObjectName(_fromUtf8("log_shape"))
        self.gridLayout_2.addWidget(self.log_shape, 0, 2, 2, 1)
        self.log_queens = QtGui.QPlainTextEdit(self.frame)
        self.log_queens.setMinimumSize(QtCore.QSize(300, 100))
        self.log_queens.setMaximumSize(QtCore.QSize(700, 100))
        self.log_queens.setBaseSize(QtCore.QSize(0, 0))
        self.log_queens.setReadOnly(True)
        self.log_queens.setObjectName(_fromUtf8("log_queens"))
        self.gridLayout_2.addWidget(self.log_queens, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        M_W.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(M_W)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        M_W.setStatusBar(self.statusbar)

        self.retranslateUi(M_W)
        QtCore.QMetaObject.connectSlotsByName(M_W)

    def retranslateUi(self, M_W):
        M_W.setWindowTitle(_translate("M_W", "N Queens Problem (GA)", None))
        self.label.setText(_translate("M_W", " Queens Number :", None))
        self.run_btn.setText(_translate("M_W", "RUN", None))
        self.label_2.setText(_translate("M_W", " Population Size :", None))
        self.pop_len.setText(_translate("M_W", "300", None))
        self.label_3.setText(_translate("M_W", " Mutation Rate :", None))
        self.mut_rate.setText(_translate("M_W", "3", None))
        self.label_4.setText(_translate("M_W", " Max Iteration :", None))
        self.max_iter.setText(_translate("M_W", "1000", None))
        self.label_5.setText(_translate("M_W", " %", None))
        self.stop_btn.setText(_translate("M_W", "STOP", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    M_W = QtGui.QMainWindow()
    ui = Ui_M_W()
    ui.setupUi(M_W)
    M_W.show()
    sys.exit(app.exec_())

